# Generated by Django 5.0.6 on 2024-05-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcatCar', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ustext', models.CharField(max_length=100, verbose_name='МЫ')),
            ],
        ),
    ]
