# Generated by Django 5.0.6 on 2024-05-16 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcatCar', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactimg', models.ImageField(upload_to='static', verbose_name='Картинка')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('mail', models.CharField(max_length=300, verbose_name='Почта')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Номер телефона', regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
