# Generated by Django 5.0.6 on 2024-05-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcatCar', '0005_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac', models.CharField(max_length=100, verbose_name='Название')),
                ('vacopis', models.CharField(max_length=300, verbose_name='Полное описание')),
            ],
        ),
    ]
