# Generated by Django 5.0.6 on 2024-05-17 03:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcatCar', '0008_sales_delete_sale'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=10, verbose_name='Вид')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('adress', models.CharField(max_length=100, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название точки')),
            ],
        ),
        migrations.RemoveField(
            model_name='sales',
            name='saleopis',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sales',
        ),
        migrations.AddField(
            model_name='sales',
            name='about',
            field=models.IntegerField(default=0, verbose_name='Сколько (в рублях)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='name',
            field=models.CharField(default=0, max_length=30, verbose_name='Промокод'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='work',
            field=models.BooleanField(default=True, verbose_name='Действует или в нет (в архиве)?'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=10, verbose_name='Цена')),
                ('code', models.CharField(max_length=10, verbose_name='Код товара')),
                ('model', models.CharField(max_length=10, verbose_name='Модель')),
                ('isSelling', models.BooleanField(verbose_name='Производится\\снято с производства (галочка = производится')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid', to='ProcatCar.carmark')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество объекта')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mebelnik', to='ProcatCar.car')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('promo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='ProcatCar.sales')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('mebels', models.ManyToManyField(blank=True, related_name='zakazi', to='ProcatCar.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('companyname', models.CharField(max_length=20, verbose_name='Название компании')),
                ('points', models.ManyToManyField(blank=True, related_name='Tochki', to='ProcatCar.points')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='ProcatCar.seller'),
        ),
    ]
