# Generated by Django 5.0.6 on 2024-05-17 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcatCar', '0009_carmark_customer_points_remove_sales_saleopis_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='object',
        ),
        migrations.RemoveField(
            model_name='car',
            name='code',
        ),
        migrations.RemoveField(
            model_name='car',
            name='company',
        ),
        migrations.RemoveField(
            model_name='car',
            name='isSelling',
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=10, verbose_name='Модель машины'),
        ),
        migrations.CreateModel(
            name='Shtraf',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cost', models.IntegerField(verbose_name='Сумма штрафа')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProcatCar.car')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
