# Generated by Django 5.0.4 on 2024-05-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProcatCar', '0011_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='points',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
    ]
