# Generated by Django 5.0.6 on 2024-05-27 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProcatCar', '0012_remove_seller_points_delete_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacks',
            old_name='dating',
            new_name='date',
        ),
        migrations.AddField(
            model_name='about',
            name='aboutimg',
            field=models.ImageField(default=True, upload_to='static', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='car',
            name='contactimg',
            field=models.ImageField(default=True, upload_to='static', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='carmark',
            name='contactimg',
            field=models.ImageField(default=True, upload_to='static', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='contactimg',
            field=models.ImageField(default=True, upload_to='static', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vac',
            name='contactimg',
            field=models.ImageField(default=True, upload_to='static', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contactimg',
            field=models.ImageField(default=True, upload_to='static', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(verbose_name='Время'),
        ),
    ]
