# Generated by Django 5.0.6 on 2024-05-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProcatCar', '0013_rename_dating_feedbacks_date_about_aboutimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='user',
        ),
    ]
